<?php
session_start();
if(isset($_SESSION['id']) && isset($_SESSION['nombre']) && isset($_SESSION['apellido']) && isset($_SESSION['id_perfil']))
{

  $explode = explode("-", $row['fecha_nacimiento']);
  $fecha_nacimiento = $explode[2]."/".$explode[1]."/".$explode[0];
?>
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?php echo $cedula;?> - Información del Visitante</title>

    <!-- Bootstrap core CSS -->
    <link href="../../vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../../css/shop-homepage.css" rel="stylesheet">

    <script language="JavaScript">
      function Salida()
      {
          if (confirm('¿Desea marcar la salida del Visitante?'))
          {
             document.salida.submit()
          }
      }
    </script> 

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Sistema de Seguridad - Conapdis</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#"><?php echo $_SESSION['nombre']." ".$_SESSION['apellido'];?>
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Salir</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <div class="col-lg-3">

          <h2 class="my-4">Menú</h2>
          <div class="list-group">
          	<a href="#" onclick="javascript:history.go(-1)" class="list-group-item active">Volver</a>
      			<a href="../vista/consulta.php" class="list-group-item">Consultar Registro</a>
      			<a href="herramienta.php" class="list-group-item">Herramientas</a>
          </div>

        </div>
        <!-- /.col-lg-3 -->
        <div class="col-lg-9">

	    <div class="tab-content">
          <div class="my-5">

          	<h4 class="my-1" ">Datos del Visitante: <?php echo $cedula;?></h4>


            <?php

            if ($est[0]) 
            {
            ?>
            <div class="form-control">


              <div class="form-group">
                
              <form name="salida" action="../controlador/salida.php" method="post" accept-charset="utf-8">

                <input type="hidden" name="cedula" value="<?php echo $cedula;?>">
                
                <label for="nombre">Nombre: </label>
                <input type="text" value="<?php echo $row['nombre'];?>" readonly>
                
                <label for="apellido">Apellido: </label>
                <input type="text" value="<?php echo $row['apellido'];?>" readonly><br/>
                
                <label for="fecha_nacimiento">Fecha de Nacimiento: </label>
                <input type="text" value="<?php echo $fecha_nacimiento;?>" readonly><br/>

                <label for="zona_residencia">Zona de Residencia</label>
                <input type="text" value="<?php echo $row['zona_residencia'];?>" readonly>
                <input type="text" value="<?php echo $row['n_certificado'];?>" readonly><br/>
                <!input type="text" name="urlImg" value="<?php echo $row['created_at'];?>" readonly>
                <!input type="text" name="urlImg" value="<?php echo $row['updated_at'];?>" readonly><br/>
                <input type=button onclick="Salida()" value="Marcar Salida" class="btn btn-primary">            
              </form>

              </div>
              

            </div>


            <?php
            }
            else 
            {
            ?>

            <div class="form-control">
              
              <form action="../vista/registrar_visita.php" method="post" accept-charset="utf-8">

                <input type="hidden" name="cedula" value="<?php echo $cedula;?>">
                
                <label for="nombre">Nombre: </label>
                <input type="text" name="nombre" value="<?php echo $row['nombre'];?>" readonly>
                
                <label for="apellido">Apellido: </label>
                <input type="text" name="apellido" value="<?php echo $row['apellido'];?>" readonly><br/>
                
                <label for="fecha_nacimiento">Fecha de Nacimiento: </label>
                <input type="text" name="fecha_nacimiento" value="<?php echo $fecha_nacimiento;?>" readonly><br/>

                <label for="zona_residencia">Zona de Residencia</label>
                <input type="text" name="zona_residencia" value="<?php echo $row['zona_residencia'];?>" readonly>
                <input type="text" name="n_certificado" value="<?php echo $row['n_certificado'];?>" readonly><br/>
                <!input type="text" name="urlImg" value="<?php echo $row['created_at'];?>" readonly>
                <!input type="text" name="urlImg" value="<?php echo $row['updated_at'];?>" readonly><br/>
                <button type="submit" class="btn btn-primary my-4">Registrar Visita</button>
            
              </form>

            </div>

            <?php
            }
            ?>
      		</div>



        </div>
        <!--/.tab-content -->

        <!-- /.col-lg-9 -->
       </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="../../vendor/jquery/jquery.min.js"></script>
    <script src="../../vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>
<?php
}
else
{
	header("Location:../../");
}