<?php
session_start();
if(isset($_SESSION['id']) && isset($_SESSION['nombre']) && isset($_SESSION['apellido']) && isset($_SESSION['id_perfil']) && $_SESSION['estatus_dato'] == 0)
{
?>
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?php echo $cedula;?> - Registrar Visitante</title>

    <!-- Bootstrap core CSS -->
    <link href="../../vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../../css/shop-homepage.css" rel="stylesheet">

    <link rel="stylesheet" href="../../css/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="../../vendor/jquery/jquery.1.12.js"></script>
    <script src="../../vendor/jquery/jquery-ui.js"></script>

    <link rel="stylesheet" type="text/css" href="../../css/datatable.min.css">
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Sistema de Seguridad - Conapdis</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#"><?php echo $_SESSION['nombre']." ".$_SESSION['apellido'];?>
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../controlador/cerrar_sesion.php">Salir</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <div class="col-lg-3">

          <h2 class="my-4">Menú</h2>
          <div class="list-group">
          	<a href="#" onclick="javascript:history.go(-1)" class="list-group-item active">Volver</a>
            <a href="../vista/novedad.php" class="list-group-item">Novedades</a>
      			<?php
            if ($_SESSION['id_perfil'] <= 1) 
            {
            ?>
              <a href="../vista/consulta.php" class="list-group-item">Consultar Registro</a>
              <a href="../vista/herramienta.php" class="list-group-item">Herramientas</a>
            <?php
            }
            elseif ($_SESSION['id_perfil'] == 2)
            {
            ?>
              <a href="../vista/consulta.php" class="list-group-item">Consultar Registro</a>
            <?php
            }
            ?>
          </div>

        </div>
        <!-- /.col-lg-3 -->
        <div class="col-lg-9">

    	    <div class="tab-content">

            <div class="my-5">

              <h4 class="my-1" ">Registrar Visitante: <?php echo $cedula;?></h4>

          		<form action="../controlador/registrar_visitante.php" method="post" accept-charset="utf-8">

                <input type="hidden" name="cedula" value="<?php echo $cedula;?>">
          			<input type="text" name="nombre" placeholder="Nombre" required>
          			<input type="text" name="apellido" placeholder="Apellido" required>
          			<input type="text" name="zona_residencia" placeholder="Zona de Residencia" required>
          			<input type="text" name="n_certificado" placeholder="N° Certificado">
                <button type="submit" class="btn btn-primary my-4">Registrar Visitante</button>

          		</form>

          	</div>
            <!-- /.my-5 -->

          </div>
          <!--/.tab-content -->

        </div>
        <!-- /.col-lg-9 -->

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Bootstrap core JavaScript -->
    <!--script src="../../vendor/jquery/jquery.min.js"></script>
    <script src="../../vendor/bootstrap/js/bootstrap.bundle.min.js"></script-->

  </body>

</html>
<?php
}
else
{
  $mensaje = "Por favor, inicie sesión para ingresar al sistema";

  echo "<script>alert('$mensaje')</script>";
  echo "<script>window.location.replace('../../');</script>";
}